[package]
name = "dumb_os"
version = "0.1.0"
authors = ["Zeeshan Hooda <zhooda@protonmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.12"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"